name: Build and Package SafronCLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install --formula cmake curl

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install -y cmake git
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install curl

      - name: Configure CMake (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          mkdir build
          cd build
          $env:VCPKG_ROOT = "$env:GITHUB_WORKSPACE\vcpkg"
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake

      - name: Build (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          cd build
          cmake --build .

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          cd build
          cmake --build . --config Release

      - name: Package
        run: |
          cd build
          cpack

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: safron-${{ runner.os }}
          path: build/*.{tar.gz,zip,msi}
